from aws_cdk import (
    Stack,
    SecretValue,
    pipelines,
    aws_codebuild as codebuild,
    aws_iam as iam,
)
import os

import aws_cdk as cdk
from constructs import Construct

from pipeline_app_stage import PipelineAppStage


class AgentPipelineStack(Stack):
    def __init__(self, scope: Construct, id: str, **kwargs):
        super().__init__(scope, id, **kwargs)

        # ❶ GitHub source (replace owner/repo and secret name)
        source = pipelines.CodePipelineSource.git_hub(
            "EducloudHQ/flash_news_agent_summarizer",  # owner/repo
            "pipeline",  # branch


        )

        # ❷ Global default: docker-enabled CodeBuild containers
        codebuild_defaults = pipelines.CodeBuildOptions(
            build_environment=codebuild.BuildEnvironment(
                privileged=True  # needed because deploy_agent.py builds & pushes a Docker image
            )
        )

        # ❸ Pipeline skeleton (self-mutating)
        pipeline = pipelines.CodePipeline(
            self,
            "BedrockAgentPipeline",
            synth=pipelines.ShellStep(
                "Synth",
                input=source,
                commands=[
                    "python -m pip install -r requirements.txt",
                    "npm i -g aws-cdk",  # CDK CLI
                    "cdk synth",
                ],
            ),
            code_build_defaults=codebuild_defaults,  # applies to every CodeBuildStep below
        )

        agent_name = "flash_news_strands_agent"

        # ⬇︎  trust policy ≈ assume_role_policy_document
        agent_role = iam.Role(
            self,
            "FlashNewsAgentRole",
            role_name=f"agentcore-{agent_name}-role",  # optional – remove if you prefer autogenerated names
            assumed_by=iam.ServicePrincipal("bedrock-agentcore.amazonaws.com"),
            inline_policies={
                "AgentCorePolicy": iam.PolicyDocument(
                    statements=[

                        # ─ Bedrock runtime calls
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=[
                                "bedrock:InvokeModel",
                                "bedrock:InvokeModelWithResponseStream",
                            ],
                            resources=["*"],
                        ),

                        # ─ Pull container layers from ECR (build role still needs push perms)
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=[
                                "ecr:BatchGetImage",
                                "ecr:GetDownloadUrlForLayer",
                            ],
                            resources=[f"arn:aws:ecr:{self.region}:{self.account}:repository/*"],
                        ),
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=["ecr:GetAuthorizationToken"],
                            resources=["*"],
                        ),

                        # ─ CloudWatch Logs
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=["logs:CreateLogGroup", "logs:DescribeLogGroups"],
                            resources=[f"arn:aws:logs:{self.region}:{self.account}:log-group:*"],
                        ),
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=["logs:CreateLogStream", "logs:PutLogEvents", "logs:DescribeLogStreams"],
                            resources=[
                                f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/bedrock-agentcore/runtimes/*",
                                f"arn:aws:logs:{self.region}:{self.account}:log-group:/aws/bedrock-agentcore/runtimes/*:log-stream:*",
                            ],
                        ),

                        # ─ X-Ray tracing
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=[
                                "xray:PutTraceSegments",
                                "xray:PutTelemetryRecords",
                                "xray:GetSamplingRules",
                                "xray:GetSamplingTargets",
                            ],
                            resources=["*"],
                        ),

                        # ─ Custom CloudWatch metrics (namespace is restricted)
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=["cloudwatch:PutMetricData"],
                            resources=["*"],
                            conditions={
                                "StringEquals": {"cloudwatch:namespace": "bedrock-agentcore"}
                            },
                        ),

                        # ─ Workload access-token APIs
                        iam.PolicyStatement(
                            effect=iam.Effect.ALLOW,
                            actions=[
                                "bedrock-agentcore:GetWorkloadAccessToken",
                                "bedrock-agentcore:GetWorkloadAccessTokenForJWT",
                                "bedrock-agentcore:GetWorkloadAccessTokenForUserId",
                            ],
                            resources=[
                                f"arn:aws:bedrock-agentcore:{self.region}:{self.account}:workload-identity-directory/default",
                                f"arn:aws:bedrock-agentcore:{self.region}:{self.account}:workload-identity-directory/default/workload-identity/{agent_name}-*",
                            ],
                        ),
                    ]
                )
            },
        )

        deploy_agent_step = pipelines.CodeBuildStep(
            "BuildPushAndUpsert",
            input=source,
            commands=[
                # 1) authenticate to ECR
                "export AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)",
                "export REPO_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/flash-news-strands",
                "aws ecr describe-repositories --repository-names flash-news-strands || "
                "aws ecr create-repository --repository-name flash-news-strands",
                "aws ecr get-login-password | docker login --username AWS --password-stdin $REPO_URI",

                # 2) multi-arch build for Graviton
                "docker buildx create --use --name agentcore_builder || true",
                "docker buildx build --platform linux/arm64 "
                "     -t $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION "
                "     --push .",

                # 3) create or update the runtime
                "python strands/upsert_runtime.py "
                "     --image $REPO_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION "
                "     --agent-name flash_news_strands_agent "
                "     --role-arn $AGENT_ROLE_ARN"
            ],
            env={
                "AWS_DEFAULT_REGION": self.region,
                "AGENT_ROLE_ARN": agent_role.role_arn  # role created elsewhere in the stack
            },
            role_policy_statements=[
                iam.PolicyStatement(
                    actions=[
                        "ecr:BatchGetImage",
                        "ecr:GetDownloadUrlForLayer",
                        "ecr:GetAuthorizationToken",
                        "bedrock-agentcore-control:*",
                        "iam:PassRole",
                        "ecr:DescribeRepositories",
                        "ecr:CreateRepository",
                        "ecr:InitiateLayerUpload",
                        "ecr:UploadLayerPart",
                        "ecr:CompleteLayerUpload",
                        "ecr:PutImage"
                    ],
                    resources=["*"],
                )
            ],
            build_environment=codebuild.BuildEnvironment(privileged=True),  # docker-in-docker
        )

        pipeline.add_stage(PipelineAppStage(self,"PipelineStage", env=cdk.Environment(account=os.getenv('CDK_DEFAULT_ACCOUNT'),
                                                   region=os.getenv('CDK_DEFAULT_REGION')),), pre=[deploy_agent_step],

                           )


